name: gradle build and test
on: [push]
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      # print all github info (e.g. branch name, commit id, etc)
      - run: |
          echo "github: ${{ toJSON(github) }}"
      # print all runner (host pc) info (e.g. os, etc)
      - run: |
          echo "runner: ${{ toJSON(runner) }}"
      - name: gradle build and test
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: |
          echo "job completed: ${{ job.status }}."