name: gradle build and test
on: [push]
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      # print all github info (e.g. branch name, commit id, etc)
      - name: github info
        run: |
          echo "${{ toJSON(github) }}"
      # print all runner (host pc) info (e.g. os, etc)
      - name: runner info
        run: |
          echo "${{ toJSON(runner) }}"

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build

      # what's the outcome?
      - run: |
          echo "job completed: ${{ job.status }}."